name: my_flutter_project
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  build_runner: ^2.4.14
  build_test: ^2.2.3
  firebase_core: ^3.11.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  

dev_dependencies:
  bloc: ^9.0.0
  bloc_test: ^10.0.0
  characters: ^1.3.0
  flutter_bloc: ^9.0.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.0-0.0.dev
  http: ^1.3.0
  hydrated_bloc: ^10.0.0 
  integration_test:
    sdk: flutter
  json_serializable: ^6.9.3
  logging: ^1.3.0
  mockito: ^5.4.5
  path: ^1.9.0
  path_provider: ^2.1.5
  quiver: ^3.2.2
  test: ^1.25.8


flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
